import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyMenu from "@/components/my/myMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="w-full h-full">
      <body className={inter.className}>
        <MyMenu />
        {children}
      </body> 
    </html>
  );
}

